name: fractol

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run executable
      run: ./fractol Mandelbrot

    - name: Clean libraries
      run: make fclean
